export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS", //можно использовать = вместо :
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CARD",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
